#!/usr/bin/env python

# This file is for building as a Godot engine module.

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

env_nd = env_modules.Clone()

env_nd.add_source_files(env.modules_sources, "*.cpp")
env_nd.add_source_files(env.modules_sources, "math/*.cpp")
env_nd.add_source_files(env.modules_sources, "nodes/*.cpp")

SConscript("mesh/SCsub")
SConscript("render/SCsub")

if env.editor_build:
    SConscript("editor/SCsub")
