#!/usr/bin/env python

Import("env")
Import("env_modules")

env_nd = env_modules.Clone()

env_nd.add_source_files(env.modules_sources, "*.cpp")
env_nd.add_source_files(env.modules_sources, "environment/*.cpp")
env_nd.add_source_files(env.modules_sources, "environment/sky/*.cpp")
env_nd.add_source_files(env.modules_sources, "wireframe_canvas/*.cpp")
