#!/usr/bin/env python

# This file is for building as a Godot GDExtension.

env = SConscript("src/godot-cpp/SConstruct")

# Add source files.
env.Append(
    CPPPATH=[
        "./,src/,../../",
        "../../math",
        "../../model",
        "../../model/mesh",
        "../../model/mesh/cell",
        "../../model/mesh/poly",
        "../../model/mesh/wire",
        "../../model/off",
        "../../nodes",
        "../../render",
        "../../render/environment",
        "../../render/environment/sky",
        "../../render/wireframe_canvas",
    ]
)

sources = (
    Glob("*.cpp")
    + Glob("src/*.cpp")
    + Glob("../../*.cpp")
    + Glob("../../math/*.cpp")
    + Glob("../../model/*.cpp")
    + Glob("../../model/mesh/*.cpp")
    + Glob("../../model/mesh/cell/*.cpp")
    + Glob("../../model/mesh/poly/*.cpp")
    + Glob("../../model/mesh/wire/*.cpp")
    + Glob("../../model/off/*.cpp")
    + Glob("../../nodes/*.cpp")
    + Glob("../../render/*.cpp")
    + Glob("../../render/environment/*.cpp")
    + Glob("../../render/environment/sky/*.cpp")
    + Glob("../../render/wireframe_canvas/*.cpp")
)

env.Append(CPPDEFINES=["GDEXTENSION"])

if env["platform"] == "windows":
    if env["OBJSUFFIX"].endswith(".obj") and not env["OBJSUFFIX"].endswith(".o.obj"):
        env["OBJSUFFIX"] = env["OBJSUFFIX"][:-4] + ".o.obj"

bin_path = "bin/"
extension_name = "godot_nd"
debug_or_release = "release" if env["target"] == "template_release" else "debug"

if not "arch_suffix" in env:
    env["arch_suffix"] = env["arch"]

if env["target"] == "editor":
    env.Append(CPPPATH=[
        "../../editor",
        "../../editor/icons",
        "../../editor/import",
        "../../editor/import/off",
        "../../editor/viewport",
    ])
    sources += (
        Glob("../../editor/*.cpp")
        + Glob("../../editor/icons/*.cpp")
        + Glob("../../editor/import/*.cpp")
        + Glob("../../editor/import/off/*.cpp")
        + Glob("../../editor/viewport/*.cpp")
    )

if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData(
            "src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml")
        )
        sources.append(doc_data)
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")

# Create the library target (e.g. libgodot_nd.linux.debug.x86_64.so).
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{0}/lib{1}.{2}.{3}.framework/{1}.{2}.{3}".format(
            bin_path,
            extension_name,
            env["platform"],
            debug_or_release,
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "{}/lib{}.{}.{}.{}{}".format(
            bin_path,
            extension_name,
            env["platform"],
            debug_or_release,
            env["arch_suffix"],
            env["SHLIBSUFFIX"],
        ),
        source=sources,
    )

Default(library)

# The rest of this file handles generating the ND icons file and GLSL header files.
import importlib.util
import os
import sys

header_builders_path = os.path.abspath(os.path.join("src/header_builders.py"))
spec = importlib.util.spec_from_file_location("header_builders", header_builders_path)
header_builders = importlib.util.module_from_spec(spec)
sys.modules["header_builders"] = header_builders
spec.loader.exec_module(header_builders)

env["BUILDERS"]["GLSL_HEADER"] = Builder(
    action=header_builders.build_raw_headers_action,
    suffix="glsl.gen.h",
)

def add_glsl_header(source_path):
    target = env.GLSL_HEADER(source_path)
    env.Depends(target, header_builders_path)
    env.Depends(target, header_builders.get_raw_header_dependencies(source_path))

target_file_path = "../../editor/icons/editor_nd_icons.gen.h"
icon_sources = Glob("icons/ND.svg") + Glob("icons/NodeND.svg")
header_builders.make_svg_icons_action([target_file_path], icon_sources, env)
